version: '3.7'

services:
  container:
    container_name: container
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend
# container creates network that is shared between other containers
networks:
  frontend:
    driver: bridge